services:
  - type: web
    name: jm-peak-performance
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /api/health
    rootDir: JMMACOR
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
    postDeployCommand: pnpm prisma db push && pnpm admin:create

  - type: cron
    name: nightly-json-backup
    env: docker
    schedule: "0 13 * * *"
    rootDir: JMMACOR
    envVars:
      - key: BACKUP_URL
        sync: false
    dockerCommand: sh -c 'curl -sS "$BACKUP_URL" -o "export-$(date +%Y%m%d).json" && ls -lh export-*.json'
