services:
  - type: web
    name: jm-peak-performance
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /api/health
    rootDir: JMMACOR
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=1024
      - key: GENERATE_SOURCEMAP
        value: false
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
