services:
  - type: web
    name: jm-peak-performance
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /api/health
    rootDir: JMMACOR
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
